// ============================================================
//  PALWORLD HELPER — Расширенные данные
// ============================================================

const DATA_EXT = {

  // ─── ПАЛЫ ДЛЯ КАЛЬКУЛЯТОРА РАЗВЕДЕНИЯ ────────────────────
  // Реальные значения Breeding Power из игровых файлов
  breedingPals: [
    { name: 'Виксы',              eng: 'Vixy',                power: 130 },
    { name: 'Ламбалль',           eng: 'Lamball',             power: 500 },
    { name: 'Чикипи',             eng: 'Chikipi',             power: 1520 },
    { name: 'Лифмунк',            eng: 'Lifmunk',             power: 340 },
    { name: 'Фоксспаркс',         eng: 'Foxparks',            power: 480 },
    { name: 'Фухо',               eng: 'Fuho',                power: 560 },
    { name: 'Гумосс',             eng: 'Gumoss',              power: 400 },
    { name: 'Рушоар',             eng: 'Rushoar',             power: 820 },
    { name: 'Горм',               eng: 'Gorirat',             power: 710 },
    { name: 'Маус',               eng: 'Mau',                 power: 1300 },
    { name: 'Маус Кризт',         eng: 'Mau Cryst',           power: 1340 },
    { name: 'Пентасан',           eng: 'Pengullet',           power: 1050 },
    { name: 'Котмалль',           eng: 'Cattiva',             power: 1040 },
    { name: 'Деспарогон',         eng: 'Depresso',            power: 600 },
    { name: 'Пуляплюш',           eng: 'Jolthog',             power: 780 },
    { name: 'Бигарде',            eng: 'Beegarde',            power: 210 },
    { name: 'Мулопен',            eng: 'Melpaca',             power: 1290 },
    { name: 'Улипоп',             eng: 'Woolipop',            power: 740 },
    { name: 'Балзам',             eng: 'Bushi',               power: 400 },
    { name: 'Якумо',              eng: 'Yakumo',              power: 1140 },
    { name: 'Анубис',             eng: 'Anubis',              power: 490 },
    { name: 'Дивинольв',          eng: 'Dinossom',            power: 740 },
    { name: 'Дивинольв Люкс',     eng: 'Dinossom Lux',        power: 790 },
    { name: 'Мерзитая',           eng: 'Cinnamoth',           power: 350 },
    { name: 'Оксалуне',           eng: 'Foxcicle',            power: 1020 },
    { name: 'Гриззболт',          eng: 'Grizzbolt',           power: 580 },
    { name: 'Орсерк',             eng: 'Orserk',              power: 500 },
    { name: 'Джормунтид',         eng: 'Jormuntide',          power: 360 },
    { name: 'Джормунтид Игнис',   eng: 'Jormuntide Ignis',    power: 370 },
    { name: 'Кельпсей',           eng: 'Kelpsea',             power: 1670 },
    { name: 'Кельпсей Игнис',     eng: 'Kelpsea Ignis',       power: 1680 },
    { name: 'Эльпидран',          eng: 'Elphidran',           power: 640 },
    { name: 'Эльпидран Акуа',     eng: 'Elphidran Aqua',      power: 660 },
    { name: 'Пиртиран',           eng: 'Pyrin',               power: 440 },
    { name: 'Пиртиран Нокт',      eng: 'Pyrin Noct',          power: 450 },
    { name: 'Люмиайр',            eng: 'Lyleen',              power: 280 },
    { name: 'Люмиайр Нокт',       eng: 'Lyleen Noct',         power: 290 },
    { name: 'Хелзейр',            eng: 'Helzephyr',           power: 360 },
    { name: 'Азуроб',             eng: 'Azurobe',             power: 350 },
    { name: 'Броншерри',          eng: 'Broncherry',          power: 590 },
    { name: 'Броншерри Акуа',     eng: 'Broncherry Aqua',     power: 600 },
    { name: 'Уловер',             eng: 'Wumpo',               power: 620 },
    { name: 'Уловер Ботан',       eng: 'Wumpo Botan',         power: 670 },
    { name: 'Маммотист',          eng: 'Mammorest',           power: 560 },
    { name: 'Маммотист Кризт',    eng: 'Mammorest Cryst',     power: 570 },
    { name: 'Рэнджиши',           eng: 'Renjishi',            power: 290 },
    { name: 'Шаолонг',            eng: 'Shaolong',            power: 260 },
    { name: 'Дандилорд',          eng: 'Dandilord',           power: 240 },
    { name: 'Эгидрон',            eng: 'Aegidron',            power: 310 },
    { name: 'Солэнн',             eng: 'Solenne',             power: 330 },
    { name: 'Сильванс',           eng: 'Silvance',            power: 320 },
    { name: 'Эйдролон',           eng: 'Eidrolon',            power: 420 },
    { name: 'Ганглер Игнис',      eng: 'Ghangler Ignis',      power: 200 },
    { name: 'Паладиус',           eng: 'Paladius',            power: 110 },
    { name: 'Некромус',           eng: 'Necromus',            power: 100 },
    { name: 'Фросталлион',        eng: 'Frostallion',         power: 80 },
    { name: 'Фросталлион Нокт',   eng: 'Frostallion Noct',    power: 90 },
    { name: 'Джетрагон',          eng: 'Jetragon',            power: 70 },
    { name: 'Беллануар',          eng: 'Bellanoir',           power: 60 },
    { name: 'Беллануар Либеро',   eng: 'Bellanoir Libero',    power: 50 },
    { name: 'Эйкзерди',           eng: 'Eikthyrdeer',         power: 760 },
    { name: 'Эйкзерди Терра',     eng: 'Eikthyrdeer Terra',   power: 770 },
    { name: 'Шэдоубик',          eng: 'Shadowbeak',          power: 120 },
    { name: 'Реиндрикс',          eng: 'Reindrix',            power: 680 },
    { name: 'Фалерис',            eng: 'Faleris',             power: 270 },
  ],

  // Особые фиксированные комбинации разведения
  specialBreeding: [
    { parent1: 'Дивинольв',   parent2: 'Мерзитая',        result: 'Орсерк',             note: 'Лучший электрик для базы' },
    { parent1: 'Джормунтид', parent2: 'Мерзитая Игнис',  result: 'Джормунтид Игнис',   note: 'Боевой брузер Огонь+Дракон' },
    { parent1: 'Фросталлион',parent2: 'Некромус',         result: 'Фросталлион Нокт',   note: 'Топ сборщик + боевой Тьма' },
    { parent1: 'Паладиус',   parent2: 'Некромус',         result: 'Шэдоубик',           note: 'Финальный босс башни 5' },
    { parent1: 'Люмиайр',    parent2: 'Хелзейр',          result: 'Люмиайр Нокт',       note: 'Тёмная версия садовода' },
    { parent1: 'Пиртиран',   parent2: 'Горм',             result: 'Пиртиран Нокт',      note: 'Ночная версия огненного' },
  ],

  // ─── ДАННЫЕ ЕДЫ ──────────────────────────────────────────
  foods: [
    { name: 'Запечённые ягоды',    icon: '🍓', nutrition: 21,  san: 1,  workSpeed: 0,  atkBonus: 0,  defBonus: 0, effect: null, automate: true,  difficulty: 1, recipe: 'Красные ягоды ×5' },
    { name: 'Хлеб',                icon: '🍞', nutrition: 27,  san: 4,  workSpeed: 0,  atkBonus: 0,  defBonus: 0, effect: null, automate: true,  difficulty: 1, recipe: 'Пшеничная мука ×3' },
    { name: 'Жареная Ламбалль',    icon: '🍖', nutrition: 45,  san: 5,  workSpeed: 30, atkBonus: 0,  defBonus: 0, effect: 'Замедляет падение SAN', automate: true, difficulty: 1, recipe: 'Мясо Ламбалль ×1' },
    { name: 'Жареная Чикипи',      icon: '🍗', nutrition: 45,  san: 5,  workSpeed: 30, atkBonus: 0,  defBonus: 0, effect: 'Замедляет падение SAN', automate: true, difficulty: 1, recipe: 'Мясо Чикипи ×1' },
    { name: 'Омлет',               icon: '🍳', nutrition: 67,  san: 7,  workSpeed: 0,  atkBonus: 10, defBonus: 0, effect: 'Атака +10%',           automate: true,  difficulty: 2, recipe: 'Яйца ×2' },
    { name: 'Картошка фри',        icon: '🍟', nutrition: 35,  san: 10, workSpeed: 0,  atkBonus: 0,  defBonus: 0, effect: 'Сопр. потере SAN +25%', automate: true,  difficulty: 1, recipe: 'Картошка ×3' },
    { name: 'Блины',               icon: '🥞', nutrition: 42,  san: 5,  workSpeed: 0,  atkBonus: 0,  defBonus: 0, effect: 'Сопр. потере SAN +25%', automate: false, difficulty: 2, recipe: 'Мука ×2 + Яйца ×1 + Молоко ×1' },
    { name: 'Грибной суп',         icon: '🍜', nutrition: 52,  san: 7,  workSpeed: 0,  atkBonus: 0,  defBonus: 0, effect: 'Замедляет потерю голода +25%', automate: false, difficulty: 2, recipe: 'Грибы ×3 + Вода ×2' },
    { name: 'Салат',               icon: '🥗', nutrition: 60,  san: 8,  workSpeed: 30, atkBonus: 0,  defBonus: 0, effect: 'Восстанавливает SAN и голод', automate: true, difficulty: 2, recipe: 'Листья ×3 + Ягоды ×3' },
    { name: 'Карбонара',           icon: '🍝', nutrition: 129, san: 16, workSpeed: 0,  atkBonus: 0,  defBonus: 20, effect: 'Защита +20%',          automate: false, difficulty: 3, recipe: 'Мука ×2 + Мясо ×1 + Яйца ×2' },
    { name: 'Гамбургер Моззарина', icon: '🍔', nutrition: 127, san: 16, workSpeed: 50, atkBonus: 0,  defBonus: 0, effect: 'Сопр. потере SAN +25%', automate: false, difficulty: 3, recipe: 'Мясо ×2 + Мука ×3 + Сыр ×1' },
    { name: 'Похлёбка Думуда',     icon: '🍲', nutrition: 140, san: 18, workSpeed: 50, atkBonus: 0,  defBonus: 0, effect: 'Замедляет потерю голода', automate: false, difficulty: 3, recipe: 'Мясо Думуда ×2 + Овощи ×3' },
    { name: 'Рагу из Эйкзерди',    icon: '🥘', nutrition: 212, san: 27, workSpeed: 0,  atkBonus: 0,  defBonus: 20, effect: 'Защита +20%',          automate: false, difficulty: 4, recipe: 'Мясо Эйкзерди ×2 + Овощи ×4' },
    { name: 'Локо-Моко Эйкзерди',  icon: '🍱', nutrition: 174, san: 22, workSpeed: 0,  atkBonus: 20, defBonus: 0, effect: 'Атака +20%',            automate: false, difficulty: 4, recipe: 'Мясо Эйкзерди ×2 + Рис ×3' },
    { name: 'Торт',                icon: '🎂', nutrition: 80,  san: 0,  workSpeed: 0,  atkBonus: 0,  defBonus: 0, effect: '⚠️ Только для разведения', automate: true, difficulty: 5, recipe: 'Мёд ×8 + Ягоды ×7 + Молоко ×7 + Яйца ×8 + Мука ×5' },
  ],

  // ─── БОССЫ БАШЕН ─────────────────────────────────────────
  bosses: [
    {
      id: 'boss1', name: 'Зо и Гриззболт', trainer: 'Зо', pal: 'Гриззболт',
      level: 10, element: 'Электро', weakness: 'Земля', icon: '⚡', difficulty: 1,
      elementColor: '#eab308', weaknessColor: '#a18560',
      rewards: ['Схематика щита', 'Очки технологий', 'Снаряжение Ур.2'],
      attacks: [
        { name: 'Удар молнии', danger: 'medium', desc: 'Прямой удар вперёд — уходи в сторону ещё до анимации' },
        { name: 'Громовой кулак', danger: 'high', desc: 'Прыжок-удар с AoE — не стой на месте, постоянно двигайся' },
        { name: 'Электрошар', danger: 'low', desc: 'Медленный снаряд по прямой — легко уклониться вбок' },
        { name: 'Ток земли', danger: 'medium', desc: 'Волна по полу — прыгай через неё' },
      ],
      tips: [
        'Используй земляных палов: Горм, Рушоар или Анубис',
        'Атакуй тренера Зо напрямую — здоровье у пары общее',
        'Держи дистанцию — ближний бой очень опасен при Lv10',
        'Схематика Гриззболта выпадает из сундука после победы',
        'Гриззболт замедляется на 30% при ударах Землёй',
      ],
      counterPals: ['Горм', 'Рушоар', 'Анубис', 'Гумосс'],
    },
    {
      id: 'boss2', name: 'Лилли и Люмиайр', trainer: 'Лилли', pal: 'Люмиайр',
      level: 20, element: 'Трава', weakness: 'Огонь', icon: '🌿', difficulty: 2,
      elementColor: '#10b981', weaknessColor: '#ef4444',
      rewards: ['Схематика оружия Ур.2', 'Очки технологий', 'Семена редких культур'],
      attacks: [
        { name: 'Цветочный залп', danger: 'medium', desc: 'Серия снарядов веером — уклоняйся зигзагом или за колонну' },
        { name: 'Корневой удар', danger: 'high', desc: 'Корни из пола по области — видишь светящийся круг — беги немедленно' },
        { name: 'Лечебная аура', danger: 'high', desc: 'Люмиайр восстанавливает HP — прерывай агрессивными атаками' },
        { name: 'Пыльца сна', danger: 'medium', desc: 'Облако — при попадании игрок засыпает. Уходи в сторону' },
      ],
      tips: [
        'Фоксспаркс с навыком «Огнемёт» — лучший выбор, режет HP Люмиайр',
        'Немедленно прерывай «Лечебную ауру» максимальным уроном',
        'Огонь даёт ×1.5 урона — не используй другие стихии',
        '5-минутный таймер — не трать время, атакуй непрерывно',
        'Рэнджиши Lv8 Огонь тоже эффективен если есть',
      ],
      counterPals: ['Фоксспаркс', 'Рэнджиши', 'Маус Игнис', 'Ганглер Игнис'],
    },
    {
      id: 'boss3', name: 'Аксель и Орсерк', trainer: 'Аксель', pal: 'Орсерк',
      level: 30, element: 'Электро / Дракон', weakness: 'Земля / Лёд', icon: '🐉', difficulty: 3,
      elementColor: '#a855f7', weaknessColor: '#93c5fd',
      rewards: ['Легендарная схематика', 'Технопоинты Ур.2', 'Редкие материалы Lv30'],
      attacks: [
        { name: 'Плазменный луч', danger: 'high', desc: 'Мощный луч по прямой — уходи строго в сторону заранее, не назад' },
        { name: 'Шаровые молнии', danger: 'medium', desc: 'Несколько шаров летают по арене — следи за траекториями' },
        { name: 'Дракон-рывок', danger: 'high', desc: 'Быстрый рывок с AoE — держи дистанцию, видишь свечение — уклоняйся' },
        { name: 'Хвостовой удар', danger: 'medium', desc: 'Удар хвостом в конус сзади — не стой позади босса' },
      ],
      tips: [
        'Орсерк двухстихийный: Земля против Электро-атак, Лёд против Дракон-атак',
        'Анубис (Земля) — идеален: высокая мобильность + правильный тип',
        'Переключайся между земляными и ледяными палами по ситуации',
        'Стой у краёв арены — уменьшает площадь покрытия атак',
        'На Hard Mode Орсерк значительно быстрее — нужен Lv35+',
      ],
      counterPals: ['Анубис', 'Оксалуне', 'Маммотист Кризт', 'Реиндрикс'],
    },
    {
      id: 'boss4', name: 'Маркус и Фалерис', trainer: 'Маркус', pal: 'Фалерис',
      level: 40, element: 'Огонь', weakness: 'Вода', icon: '🔥', difficulty: 4,
      elementColor: '#ef4444', weaknessColor: '#3b82f6',
      rewards: ['Легендарная схематика оружия', 'Технопоинты Ур.3', 'Ультра сферы'],
      attacks: [
        { name: 'Огненное пике', danger: 'high', desc: 'Атака пикирования сверху — откатывайся за секунду до касания' },
        { name: 'Кольцо огня', danger: 'critical', desc: 'Огонь кругом от Фалерис — беги немедленно при появлении' },
        { name: 'Огненный шторм', danger: 'medium', desc: 'Серия снарядов — уклоняйся зигзагом непрерывно' },
        { name: 'Горящий след', danger: 'medium', desc: 'Оставляет огонь на полу — не наступай на красные зоны' },
      ],
      tips: [
        'Ракетная пусковая установка даёт огромный разовый урон — используй',
        'Джормунтид (Вода) с пассивкой Легенда — лучший выбор',
        'Фалерис летает — твой пал должен уметь бить по воздуху',
        'Держи 5+ зелий щита максимального уровня для личной защиты',
        'Маркус атакует игрока — можно использовать это для разделения',
      ],
      counterPals: ['Джормунтид', 'Азуроб', 'Кельпсей', 'Шаолонг'],
    },
    {
      id: 'boss5', name: 'Виктор и Шэдоубик', trainer: 'Виктор', pal: 'Шэдоубик',
      level: 50, element: 'Тьма', weakness: 'Дракон', icon: '👑', difficulty: 5,
      elementColor: '#a855f7', weaknessColor: '#f87171',
      rewards: ['Топ легендарная схематика', 'Макс. технопоинты', 'Эксклюзивные материалы', 'Схематика Hard Mode'],
      attacks: [
        { name: 'Луч тьмы', danger: 'critical', desc: 'Мощнейший луч на всю арену — прячься за колонны немедленно' },
        { name: 'Теневая волна', danger: 'high', desc: 'AoE волна по полу — прыгай через неё в последний момент' },
        { name: 'Клонирование теней', danger: 'medium', desc: 'Создаёт иллюзии — атакуй настоящего (он немного ярче)' },
        { name: 'Теневой прыжок', danger: 'high', desc: 'Телепортация с ударом — постоянно двигайся, не стой' },
      ],
      tips: [
        'Финальный босс — нужно ТОЛЬКО легендарное снаряжение',
        'Джетрагон (Дракон) — топ выбор: ×1.5 урона + скорость',
        'Прячься за колонны от «Луча тьмы» — он смертелен',
        '5+ зелий восстановления HP максимального уровня обязательны',
        'Hard Mode открывает эксклюзивные легендарные схематики',
        'Некромус тоже хорош — высокое HP и урон Тьмы/Дракона',
      ],
      counterPals: ['Джетрагон', 'Некромус', 'Джормунтид Игнис', 'Паладиус'],
    },
  ],

  // ─── ЗОЛОТО: МЕТОДЫ ФАРМА ────────────────────────────────
  goldItems: [
    {
      name: 'Виксы на Ранчо',       icon: '🦊', method: 'Пассивный (Ранчо)',
      income: 'low',  incomeLabel: '~200 монет/рейс',  difficulty: 1, diffLabel: 'Очень лёгкий',
      type: 'passive',
      tip: 'Лучший старт для новичков. Виксы роют монеты, стрелы и сферы автоматически. Доступны с раннего уровня, не требуют ресурсов.',
    },
    {
      name: 'Маус / Маус Кризт на Ранчо', icon: '🐱', method: 'Пассивный (Ранчо)',
      income: 'medium', incomeLabel: '~500 монет/рейс', difficulty: 2, diffLabel: 'Лёгкий',
      type: 'passive',
      tip: 'Лучший пассивный фарм золота в игре. Маус Кризт немного выгоднее обычного. Просто помести на Ранчо и забудь — монеты копятся сами.',
    },
    {
      name: 'Думуд Гилд в пати',    icon: '💰', method: 'В активной команде',
      income: 'medium', incomeLabel: '+% к дропу с врагов', difficulty: 2, diffLabel: 'Лёгкий',
      type: 'passive',
      tip: 'Партнёрский навык Думуд Гилда увеличивает золото, падающее с убитых врагов. Держи в команде во время фарма зон и подземелий.',
    },
    {
      name: 'Фарм данжей',           icon: '🚪', method: 'Активный (данжи)',
      income: 'high', incomeLabel: '5000–50000 за заход', difficulty: 3, diffLabel: 'Средний',
      type: 'active',
      tip: 'Сундуки в данжах содержат драгоценные камни (рубины, сапфиры, бриллианты) стоимостью 5000–10000 монет каждый. Лучший активный метод на средних уровнях.',
    },
    {
      name: 'Продажа Салата ×9999',  icon: '🥗', method: 'Производство + продажа',
      income: 'very-high', incomeLabel: '~1.1 млн монет', difficulty: 4, diffLabel: 'Требует автоматизации',
      type: 'production',
      tip: 'Эндгейм-метод. Автоматизируй производство Салата на ферме, собери стак ×9999 и продай торговцу. Лучший метод для опытных игроков с развитой базой.',
    },
    {
      name: 'Легендарные сферы',     icon: '⚽', method: 'Крафт + продажа',
      income: 'high', incomeLabel: '~4500 монет за штуку', difficulty: 4, diffLabel: 'Требует ресурсов',
      type: 'production',
      tip: 'При избытке ресурсов крафти Легендарные сферы и продавай. Хорошая цена за единицу, не требует отдельной базы.',
    },
    {
      name: 'Слитки Пал-металла',    icon: '🔩', method: 'Добыча + плавка + продажа',
      income: 'medium', incomeLabel: '~80 монет за штуку', difficulty: 3, diffLabel: 'Средний',
      type: 'production',
      tip: 'Стабильный средний доход. Выдели отдельную добывающую базу с Эгидронами рядом с рудником — постоянный поток слитков.',
    },
    {
      name: 'Дроп с Альфа-боссов',   icon: '👹', method: 'Активный (охота)',
      income: 'high', incomeLabel: 'Зависит от босса', difficulty: 4, diffLabel: 'Сложный',
      type: 'active',
      tip: 'Все «Ценные предметы» и «Реликвии» из дропа с полевых Альфа-боссов — продавай немедленно. Боссы возрождаются каждый ~1 час.',
    },
  ],

  // ─── ДЕРЕВО ТЕХНОЛОГИЙ ───────────────────────────────────
  techTree: [
    // Уровень 1 (1-5)
    { id: 't1',  name: 'Примитивный верстак',   level: 1,  pts: 1, tier: 1, cat: 'Крафт',    deps: [],       priority: 'high',   tip: 'Первое и главное здание — открывает базовый крафт инструментов' },
    { id: 't2',  name: 'Костёр',                 level: 1,  pts: 1, tier: 1, cat: 'Еда',      deps: [],       priority: 'high',   tip: 'Готовка базовой еды. Изучи сразу — жареное мясо восстанавливает SAN' },
    { id: 't3',  name: 'Деревянный ящик',        level: 2,  pts: 1, tier: 1, cat: 'База',     deps: ['t1'],   priority: 'high',   tip: 'Хранение ресурсов — строй сразу несколько' },
    { id: 't4',  name: 'Паль-сфера',             level: 2,  pts: 1, tier: 1, cat: 'Поимка',  deps: [],       priority: 'high',   tip: 'Основа всего — без сфер нет палов' },
    { id: 't5',  name: 'Спальный мешок',         level: 2,  pts: 1, tier: 1, cat: 'Выживание',deps: [],      priority: 'medium', tip: 'Сохранение через сон — полезно' },
    { id: 't6',  name: 'Кормушка',               level: 4,  pts: 2, tier: 1, cat: 'База',     deps: ['t3'],   priority: 'high',   tip: 'Автокормление палов на базе — ОБЯЗАТЕЛЬНА перед наймом рабочих' },
    // Уровень 2 (6-15)
    { id: 't7',  name: 'Верстак Ур.2',           level: 6,  pts: 2, tier: 2, cat: 'Крафт',    deps: ['t1'],   priority: 'high',   tip: 'Открывает металлические рецепты и инструменты 2-го уровня' },
    { id: 't8',  name: 'Кухонная плита',         level: 7,  pts: 2, tier: 2, cat: 'Еда',      deps: ['t2'],   priority: 'high',   tip: 'Готовка еды с бонусами к работе и SAN. Изучи как можно раньше' },
    { id: 't9',  name: 'Ранчо',                  level: 5,  pts: 2, tier: 2, cat: 'База',     deps: ['t6'],   priority: 'high',   tip: 'Пассивная добыча ресурсов — Виксы (золото), Бигарде (мёд), Маус (монеты)' },
    { id: 't10', name: 'Горячий источник',       level: 9,  pts: 3, tier: 2, cat: 'База',     deps: ['t6'],   priority: 'high',   tip: 'КРИТИЧЕСКИ ВАЖЕН. Восстанавливает SAN палов. Без него рабочие бастуют' },
    { id: 't11', name: 'Инкубатор яиц',          level: 7,  pts: 2, tier: 2, cat: 'Разведение',deps: ['t9'], priority: 'medium', tip: 'Ускоряет инкубацию яиц палов. Нужен при активном разведении' },
    { id: 't12', name: 'Электростанция',         level: 15, pts: 3, tier: 2, cat: 'База',     deps: ['t7'],   priority: 'medium', tip: 'Нужна для всего электрооборудования. Требует пала-электрика (Орсерк)' },
    { id: 't13', name: 'Медицинская станция',    level: 12, pts: 3, tier: 2, cat: 'База',     deps: ['t7'],   priority: 'medium', tip: 'Автолечение палов на базе. Нужен пал-медик (Сильванс)' },
    // Уровень 3 (16-25)
    { id: 't14', name: 'Сущностный конденсор',   level: 14, pts: 3, tier: 3, cat: 'Прокачка', deps: ['t7'],   priority: 'high',   tip: 'Жертвуй дубликатами для повышения ранга пала. Изучи как можно раньше!' },
    { id: 't15', name: 'Верстак Ур.3',           level: 18, pts: 4, tier: 3, cat: 'Крафт',    deps: ['t7'],   priority: 'high',   tip: 'Открывает снаряжение высокого уровня и продвинутые рецепты' },
    { id: 't16', name: 'Ферма разведения',       level: 19, pts: 4, tier: 3, cat: 'Разведение',deps: ['t9'], priority: 'high',   tip: 'Ключевая технология — позволяет разводить палов для получения сильных потомков' },
    { id: 't17', name: 'Стойка мониторинга',     level: 15, pts: 3, tier: 3, cat: 'База',     deps: ['t6'],   priority: 'high',   tip: 'Управление заданиями палов — отключай ненужные задачи у специалистов' },
    { id: 't18', name: 'Усил. электростанция',   level: 22, pts: 4, tier: 3, cat: 'База',     deps: ['t12'],  priority: 'medium', tip: 'Больше мощности для крупных баз с большим числом станций' },
    // Уровень 4 (26-40)
    { id: 't19', name: 'Верстак Ур.4',           level: 30, pts: 5, tier: 4, cat: 'Крафт',    deps: ['t15'],  priority: 'high',   tip: 'Снаряжение топ-уровня. Нужен для подготовки к финальным боссам' },
    { id: 't20', name: 'Алтарь призыва',         level: 33, pts: 5, tier: 4, cat: 'Рейды',    deps: ['t15'],  priority: 'high',   tip: 'Вызов Беллануар для рейдов. Нужны Плиты Беллануар из данжей' },
    { id: 't21', name: 'Рабочий справочник',     level: 25, pts: 4, tier: 4, cat: 'Прокачка', deps: ['t14'],  priority: 'medium', tip: 'Повышает рабочий навык пала. Используй вместе с Конденсором' },
    // Уровень 5 (41+)
    { id: 't22', name: 'Верстак легенды',        level: 45, pts: 6, tier: 5, cat: 'Крафт',    deps: ['t19'],  priority: 'high',   tip: 'Крафт легендарного снаряжения по найденным схематикам из данжей' },
    { id: 't23', name: 'Легенд. сфера Пала',     level: 44, pts: 5, tier: 5, cat: 'Поимка',   deps: ['t19'],  priority: 'medium', tip: 'Максимальный шанс поимки. Нужна для легендарных палов' },
  ],

  // ─── ЛОКАЦИИ НА КАРТЕ ────────────────────────────────────
  // Координаты нормализованы под canvas 700×500 (условные)
  mapLocations: [
    // Легендарные палы
    { id: 'ml1', name: 'Фросталлион',      type: 'legendary', x: 140, y: 60,  desc: 'Астральные горы — крайний север. Лв.50+', icon: '❄️', color: '#93c5fd' },
    { id: 'ml2', name: 'Фросталлион Нокт', type: 'legendary', x: 180, y: 80,  desc: 'Тёмные зоны севера, рядом с Фросталлионом', icon: '🖤', color: '#93c5fd' },
    { id: 'ml3', name: 'Некромус',          type: 'legendary', x: 160, y: 380, desc: 'Северо-запад, Глубокие дюны. Часто с Паладиусом', icon: '💀', color: '#a855f7' },
    { id: 'ml4', name: 'Паладиус',          type: 'legendary', x: 185, y: 395, desc: 'Глубокие дюны рядом с Некромусом', icon: '⚪', color: '#a855f7' },
    { id: 'ml5', name: 'Джетрагон',         type: 'legendary', x: 610, y: 90,  desc: 'Кратер вулкана, дальний восток. Очень быстрый', icon: '🐉', color: '#f87171' },
    // Данжи
    { id: 'md1', name: 'Данж: Равнины',    type: 'dungeon', x: 360, y: 280, desc: 'Центральные равнины. Ур. 15–25', icon: '🚪', color: '#fbbf24' },
    { id: 'md2', name: 'Данж: Пустыня',    type: 'dungeon', x: 480, y: 380, desc: 'Пустынная зона. Ур. 25–35', icon: '🏜️', color: '#fbbf24' },
    { id: 'md3', name: 'Данж: Снег',       type: 'dungeon', x: 260, y: 130, desc: 'Снежные горы севера. Ур. 35–45', icon: '🏔️', color: '#fbbf24' },
    { id: 'md4', name: 'Данж: Вулкан',     type: 'dungeon', x: 560, y: 180, desc: 'Вулканический район. Ур. 40–50', icon: '🌋', color: '#fbbf24' },
    // Торговцы
    { id: 'mm1', name: 'Торговец: Деревня', type: 'merchant', x: 340, y: 310, desc: 'Деревня Сандстрим — базовые ресурсы и сферы', icon: '🛒', color: '#10b981' },
    { id: 'mm2', name: 'Торговец: Рыбак',   type: 'merchant', x: 420, y: 420, desc: 'Рыбацкая деревня — рыба, снасти, редкие семена', icon: '🎣', color: '#10b981' },
    { id: 'mm3', name: 'Торговец: Форт',    type: 'merchant', x: 500, y: 300, desc: 'Форт — редкие схематики и снаряжение', icon: '🏪', color: '#10b981' },
    // Месторождения
    { id: 'mo1', name: 'Железо: Горы',      type: 'ore', x: 290, y: 160, desc: 'Крупное железное месторождение в горах', icon: '⛏️', color: '#6b7280' },
    { id: 'mo2', name: 'Уголь: Юг',         type: 'ore', x: 430, y: 440, desc: 'Угольное месторождение — пустынный юг', icon: '🪨', color: '#6b7280' },
    { id: 'mo3', name: 'Сера: Вулкан',      type: 'ore', x: 540, y: 210, desc: 'Серное месторождение у вулкана', icon: '🟡', color: '#6b7280' },
    { id: 'mo4', name: 'Кварц: Север',      type: 'ore', x: 220, y: 110, desc: 'Кварцевые жилы в снежных горах', icon: '💠', color: '#6b7280' },
    // Башни
    { id: 'mt1', name: '🗼 Башня 1: Зо',     type: 'tower', x: 350, y: 300, desc: 'Башня 1 — Зо и Гриззболт. Ур. 10+', icon: '🗼', color: '#f59e0b' },
    { id: 'mt2', name: '🗼 Башня 2: Лилли',  type: 'tower', x: 250, y: 380, desc: 'Башня 2 — Лилли и Люмиайр. Ур. 20+', icon: '🗼', color: '#f59e0b' },
    { id: 'mt3', name: '🗼 Башня 3: Аксель', type: 'tower', x: 470, y: 150, desc: 'Башня 3 — Аксель и Орсерк. Ур. 30+', icon: '🗼', color: '#f59e0b' },
    { id: 'mt4', name: '🗼 Башня 4: Маркус', type: 'tower', x: 150, y: 440, desc: 'Башня 4 — Маркус и Фалерис. Ур. 40+', icon: '🗼', color: '#f59e0b' },
    { id: 'mt5', name: '🗼 Башня 5: Виктор', type: 'tower', x: 600, y: 430, desc: 'Башня 5 — Виктор и Шэдоубик. Ур. 50+', icon: '🗼', color: '#f59e0b' },
  ],
};
