// ============================================================
//  PAL IMAGES — Полная база данных иконок палов (299 палов)
//  Источник: cdn.paldb.cc / Официальные текстуры Palworld
// ============================================================

const PAL_IMG_BASE = 'https://cdn.paldb.cc/image/Pal/Texture/PalIcon/Normal/';

// Complete Pal internal ID mapping from paldb.cc (299 pals)
const PAL_INTERNAL = {
  'Lamball': 'SheepBall',
  'Cattiva': 'PinkCat',
  'Chikipi': 'ChickenPal',
  'Lifmunk': 'Carbunclo',
  'Fuack': 'BluePlatypus',
  'Fuack Ignis': 'BluePlatypus_Fire',
  'Vixy': 'CuteFox',
  'Celaray': 'FlyingManta',
  'Celaray Lux': 'FlyingManta_Thunder',
  'Cremis': 'WoolFox',
  'Croajiro': 'KendoFrog',
  'Croajiro Noct': 'KendoFrog_Dark',
  'Herbil': 'LeafMomonga',
  'Teafant': 'Ganesha',
  'Gumoss': 'PlantSlime',
  'Pupperai': 'SamuraiDog',
  'Clovee': 'CloverFairy',
  'Jolthog': 'Hedgehog',
  'Jolthog Cryst': 'Hedgehog_Ice',
  'Depresso': 'NegativeKoala',
  'Pengullet': 'Penguin',
  'Pengullet Lux': 'Penguin_Electric',
  'Penking': 'CaptainPenguin',
  'Penking Lux': 'CaptainPenguin_Black',
  'Hoocrates': 'WizardOwl',
  'Melpaca': 'Alpaca',
  'Kingpaca': 'KingAlpaca',
  'Kingpaca Cryst': 'KingAlpaca_Ice',
  'Daedream': 'DreamDemon',
  'Tanzee': 'Monkey',
  'Tanzee Ignis': 'Monkey_Fire',
  'Nox': 'NightFox',
  'Flambelle': 'LavaGirl',
  'Rooby': 'FlameBambi',
  'Mau': 'Bastet',
  'Mau Cryst': 'Bastet_Ice',
  'Rushoar': 'Boar',
  'Foxparks': 'Kitsunebi',
  'Foxparks Cryst': 'Kitsunebi_Ice',
  'Killamari': 'NegativeOctopus',
  'Killamari Primo': 'NegativeOctopus_Neutral',
  'Fuddler': 'CuteMole',
  'Eikthyrdeer': 'Deer',
  'Eikthyrdeer Terra': 'Deer_Ground',
  'Direhowl': 'Garm',
  'Caprity': 'BerryGoat',
  'Caprity Noct': 'BerryGoat_Dark',
  'Swee': 'MopBaby',
  'Sweepa': 'MopKing',
  'Turtacle': 'TentacleTurtle',
  'Turtacle Terra': 'TentacleTurtle_Ground',
  'Hangyu': 'WindChimes',
  'Hangyu Cryst': 'WindChimes_Ice',
  'Woolipop': 'SweetsSheep',
  'Woolipop Terra': 'SweetsSheep_Ground',
  'Mozzarina': 'CowPal',
  'Azurobe': 'BlueDragon',
  'Azurobe Cryst': 'BlueDragon_Ice',
  'Sparkit': 'ElecCat',
  'Kelpsea': 'Kelpie',
  'Kelpsea Ignis': 'Kelpie_Fire',
  'Ribbuny': 'PinkRabbit',
  'Ribbuny Botan': 'PinkRabbit_Grass',
  'Jelliette': 'JellyfishFairy',
  'Jellroy': 'JellyfishGhost',
  'Amione': 'ClioneTwins',
  'Gloopie': 'OctopusGirl',
  'Gloopie Primo': 'OctopusGirl_Neutral',
  'Galeclaw': 'Eagle',
  'Wispaw': 'GhostBlackCat',
  'Nitewing': 'HawkBird',
  'Tombat': 'CatBat',
  'Tocotoco': 'ColorfulBird',
  'Univolt': 'Kirin',
  'Univolt Cryst': 'Kirin_Ice',
  'Gobfin': 'SharkKid',
  'Gobfin Ignis': 'SharkKid_Fire',
  'Loupmoon': 'Werewolf',
  'Loupmoon Cryst': 'Werewolf_Ice',
  'Cawgnito': 'DarkCrow',
  'Arsox': 'FlameBuffalo',
  'Muffly': 'FluffyBird',
  'Bristla': 'LittleBriarRose',
  'Cinnamoth': 'CuteButterfly',
  'Puffolt': 'ElecPomeranian',
  'Elphidran': 'FairyDragon',
  'Elphidran Aqua': 'FairyDragon_Water',
  'Vanwyrm': 'BirdDragon',
  'Vanwyrm Cryst': 'BirdDragon_Ice',
  'Felbat': 'CatVampire',
  'Vaelet': 'VioletFairy',
  'Beegarde': 'SoldierBee',
  'Elizabee': 'QueenBee',
  'Lovander': 'PinkLizard',
  'Grintale': 'NaughtyCat',
  'Tarantriss': 'PurpleSpider',
  'Polapup': 'IceSeal',
  'Polapup Terra': 'IceSeal_Ground',
  'Leezpunk': 'LizardMan',
  'Leezpunk Ignis': 'LizardMan_Fire',
  'Gorirat': 'Gorilla',
  'Gorirat Terra': 'Gorilla_Ground',
  'Surfent': 'Serpent',
  'Surfent Terra': 'Serpent_Ground',
  'Robinquill': 'RobinHood',
  'Robinquill Terra': 'RobinHood_Ground',
  'Flopie': 'FlowerRabbit',
  'Wixen': 'FoxMage',
  'Wixen Noct': 'FoxMage_Dark',
  'Katress': 'CatMage',
  'Katress Ignis': 'CatMage_Fire',
  'Helzephyr': 'HadesBird',
  'Helzephyr Lux': 'HadesBird_Electric',
  'Elgrove': 'GrassMinotaur',
  'Elgrove Cryst': 'GrassMinotaur_Ice',
  'Lunaris': 'Mutant',
  'Fenglope': 'FengyunDeeper',
  'Fenglope Lux': 'FengyunDeeper_Electric',
  'Dinossom': 'FlowerDinosaur',
  'Dinossom Lux': 'FlowerDinosaur_Electric',
  'Bushi': 'Ronin',
  'Bushi Noct': 'Ronin_Dark',
  'Munchill': 'IceCrocodile',
  'Mammorest': 'GrassMammoth',
  'Mammorest Cryst': 'GrassMammoth_Ice',
  'Finsider': 'StuffedShark',
  'Finsider Ignis': 'StuffedShark_Fire',
  'Petallia': 'FlowerDoll',
  'Petallia Ignis': 'FlowerDoll_Fire',
  'Leafan': 'PandaGirl',
  'Incineram': 'Baphomet',
  'Incineram Noct': 'Baphomet_Dark',
  'Dazzi': 'RaijinDaughter',
  'Dazzi Noct': 'RaijinDaughter_Water',
  'Pyrin': 'FireKirin',
  'Pyrin Noct': 'FireKirin_Dark',
  'Relaxaurus': 'LazyDragon',
  'Relaxaurus Lux': 'LazyDragon_Electric',
  'Foxcicle': 'IceFox',
  'Beakon': 'ThunderBird',
  'Beakon Cryst': 'ThunderBird_Ice',
  'Ghangler': 'GhostAnglerfish',
  'Ghangler Ignis': 'GhostAnglerfish_Fire',
  'Rayhound': 'ThunderDog',
  'Rayhound Cryst': 'ThunderDog_Ice',
  'Menasting': 'DarkScorpion',
  'Menasting Terra': 'DarkScorpion_Ground',
  'Needoll': 'CactusDoll',
  'Needoll Noct': 'CactusDoll_Dark',
  'Reindrix': 'IceDeer',
  'Mossanda': 'GrassPanda',
  'Mossanda Lux': 'GrassPanda_Electric',
  'Chillet': 'WeaselDragon',
  'Chillet Ignis': 'WeaselDragon_Fire',
  'Ragnahawk': 'RedArmorBird',
  'Moldron': 'VolcanoDragon',
  'Moldron Cryst': 'VolcanoDragon_Ice',
  'Palumba': 'TropicalOstrich',
  'Digtoise': 'DrillGame',
  'Broncherry': 'SakuraSaurus',
  'Broncherry Aqua': 'SakuraSaurus_Water',
  'Dumud': 'LazyCatfish',
  'Dumud Gild': 'LazyCatfish_Gold',
  'Braloha': 'Plesiosaur',
  'Kitsun': 'AmaterasuWolf',
  'Kitsun Noct': 'AmaterasuWolf_Dark',
  'Blazehowl': 'Manticore',
  'Blazehowl Noct': 'Manticore_Dark',
  'Warsect': 'HerculesBeetle',
  'Warsect Terra': 'HerculesBeetle_Ground',
  'Frostplume': 'SnowPeafowl',
  'Majex': 'DarkFlameFox',
  'Sibelyx': 'WhiteMoth',
  'Sibelyx Primo': 'WhiteMoth_Neutral',
  'Maraith': 'GhostBeast',
  'Shroomer': 'MushroomDragon',
  'Shroomer Noct': 'MushroomDragon_Dark',
  'Icelyn': 'IceWitch',
  'Gildra': 'MummyPal',
  'Jormuntide': 'Umihebi',
  'Jormuntide Ignis': 'Umihebi_Fire',
  'Suzaku': 'Suzaku',
  'Suzaku Aqua': 'Suzaku_Water',
  'Dazemu': 'FeatherOstrich',
  'Quivern': 'SkyDragon',
  'Quivern Botan': 'SkyDragon_Grass',
  'Lullu': 'LeafPrincess',
  'Kikit': 'SmallArmadillo',
  'Yakumo': 'GuardianDog',
  'Skutlass': 'SwordCutlassfish',
  'Skutlass Ignis': 'SwordCutlassfish_Fire',
  'Reptyro': 'VolcanicMonster',
  'Reptyro Cryst': 'VolcanicMonster_Ice',
  'Starryon': 'NightBlueHorse',
  'Starryon Primo': 'NightBlueHorse_Neutral',
  'Pierdon': 'RockBeast',
  'Pierdon Cryst': 'RockBeast_Ice',
  'Cryolinx': 'WhiteTiger',
  'Cryolinx Terra': 'WhiteTiger_Ground',
  'Snugloo': 'SmallYeti',
  'Wumpo': 'Yeti',
  'Wumpo Botan': 'Yeti_Grass',
  'Sootseer': 'CandleGhost',
  'Carnibora': 'VenusFlytrap',
  'Blazamut': 'KingBahamut',
  'Blazamut Ryu': 'KingBahamut_Dragon',
  'Dualith': 'GrassGolem',
  'Dualith Noct': 'GrassGolem_Dark',
  'Anubis': 'Anubis',
  'Sekhmet': 'Sekhmet',
  'Prixter': 'ScorpionMan',
  'Prixter Lux': 'ScorpionMan_Electric',
  'Tetroise': 'CubeTurtle',
  'Tetroise Primo': 'CubeTurtle_Neutral',
  'Nyafia': 'BadCatgirl',
  'Mimog': 'MimicDog',
  'Xenovader': 'DarkAlien',
  'Xenogard': 'WhiteAlienDragon',
  'Prunelia': 'BlueberryFairy',
  'Nitemary': 'GhostRabbit',
  'Nitemary Botan': 'GhostRabbit_Grass',
  'Smokie': 'BlackPuppy',
  'Smokie Cryst': 'BlackPuppy_Ice',
  'Omascul': 'MysteryMask',
  'Whalaska': 'IceNarwhal',
  'Whalaska Ignis': 'IceNarwhal_Fire',
  'Verdash': 'GrassRabbitMan',
  'Splatterina': 'GrimGirl',
  'Gildane': 'GoldenHorse',
  'Dogen': 'SifuDog',
  'Bulldosu': 'SumoDog',
  'Celesdir': 'WhiteDeer',
  'Celesdir Noct': 'WhiteDeer_Dark',
  'Astegon': 'BlackMetalDragon',
  'Knocklem': 'WingGolem',
  'Knocklem Ignis': 'WingGolem_Fire',
  'Silvegis': 'WhiteShieldDragon',
  'Azurmane': 'BlueThunderHorse',
  'Valentail': 'LongCat',
  'Snock': 'ElecSnail',
  'Snock Terra': 'ElecSnail_Ground',
  'Souffline': 'DandelionGirl',
  'Lapiron': 'BrownRabbit',
  'Hoodle': 'HoodGhost',
  'Slowatt': 'ElecLizard',
  'Bakemi': 'OniGhostGirl',
  'Solmora': 'KingSunfish',
  'Solmora Lux': 'KingSunfish_Thunder',
  'Lapure': 'SleeveRabbit',
  'Eidrolon': 'GhostDragon',
  'Eidrolon Ignis': 'GhostDragon_Fire',
  'Dynamoff': 'ThunderFluffyBird',
  'Tropicaw': 'RedFlowerBird',
  'Flaracle': 'FoxExorcist',
  'Ophydia': 'LotusDragon',
  'Dupin': 'ClownRabbit',
  'Roujay': 'ThiefBird',
  'Venusa': 'SnakeGirl',
  'Mycora': 'MushroomLady',
  'Loomen': 'LanternButler',
  'Wistella': 'MoonChild',
  'Solenne': 'MonochromeQueen',
  'Renjishi': 'KabukiMan',
  'Aegidron': 'DomeArmorDragon',
  'Grizzbolt': 'ElecPanda',
  'Lyleen': 'LilyQueen',
  'Lyleen Noct': 'LilyQueen_Dark',
  'Orserk': 'ThunderDragonMan',
  'Faleris': 'Horus',
  'Faleris Aqua': 'Horus_Water',
  'Shadowbeak': 'BlackGriffon',
  'Selyne': 'MoonQueen',
  'Bastigor': 'SnowTigerBeastman',
  'Shaolong': 'BlueSkyDragon',
  'Silvance': 'Mothman',
  'Dandilord': 'FlowerPrince',
  'Bellanoir': 'NightLady',
  'Bellanoir Libero': 'NightLady_Dark',
  'Xenolord': 'DarkMechaDragon',
  'Hartalis': 'LegendDeer',
  'Paladius': 'SaintCentaur',
  'Necromus': 'BlackCentaur',
  'Frostallion': 'IceHorse',
  'Frostallion Noct': 'IceHorse_Dark',
  'Neptilius': 'PoseidonOrca',
  'Jetragon': 'JetDragon',
  'Panthalus': 'KingWhale',
  'Astralym': 'WorldTreeDragon',
  'Green Slime': 'YakushimaMonster001',
  'Blue Slime': 'YakushimaMonster001_Blue',
  'Red Slime': 'YakushimaMonster001_Red',
  'Purple Slime': 'YakushimaMonster001_Purple',
  'Illuminant Slime': 'YakushimaMonster001_Pink',
  'Rainbow Slime': 'YakushimaMonster001_Rainbow',
  'Enchanted Sword': 'YakushimaMonster002',
  'Cave Bat': 'YakushimaMonster003',
  'Illuminant Bat': 'YakushimaMonster003_Purple',
  'Eye of Cthulhu': 'YakushimaBoss001',
  'Demon Eye': 'YakushimaBoss001_Small',
};



// Русско-английский маппинг для надёжного поиска по любому названию
const RU_TO_ENG = {
  'Рэнджиши': 'Renjishi',
  'Шаолонг': 'Shaolong',
  'Дандилорд': 'Dandilord',
  'Эгидрон': 'Aegidron',
  'Солэнн': 'Solenne',
  'Орсерк': 'Orserk',
  'Сильванс': 'Silvance',
  'Эйдролон': 'Eidrolon',
  'Фросталлион Нокт': 'Frostallion Noct',
  'Селесдир Нокт': 'Celesdir Noct',
  'Селесдир': 'Celesdir',
  'Бигарде': 'Beegarde',
  'Бигард': 'Beegarde',
  'Анубис': 'Anubis',
  'Беллануар Либеро': 'Bellanoir Libero',
  'Беллануар': 'Bellanoir',
  'Ганглер Игнис': 'Ghangler Ignis',
  'Джетрагон': 'Jetragon',
  'Некромус': 'Necromus',
  'Паладиус': 'Paladius',
  'Фросталлион': 'Frostallion',
  'Джормунтид Игнис': 'Jormuntide Ignis',
  'Джормунтид': 'Jormuntide',
  'Виксы': 'Vixy',
  'Ламбалль': 'Lamball',
  'Чикипи': 'Chikipi',
  'Лифмунк': 'Lifmunk',
  'Фоксспаркс': 'Foxparks',
  'Фухо': 'Fuack',
  'Гумосс': 'Gumoss',
  'Рушоар': 'Rushoar',
  'Горм': 'Gorirat',
  'Маус': 'Mau',
  'Маус Кризт': 'Mau Cryst',
  'Пентасан': 'Pengullet',
  'Котмалль': 'Cattiva',
  'Деспарогон': 'Depresso',
  'Пуляплюш': 'Jolthog',
  'Мулопен': 'Melpaca',
  'Улипоп': 'Woolipop',
  'Балзам': 'Bushi',
  'Якумо': 'Yakumo',
  'Дивинольв': 'Dinossom',
  'Дивинольв Люкс': 'Dinossom Lux',
  'Мерзитая': 'Cinnamoth',
  'Оксалуне': 'Foxcicle',
  'Гриззболт': 'Grizzbolt',
  'Кельпсей': 'Kelpsea',
  'Кельпсей Игнис': 'Kelpsea Ignis',
  'Эльпидран': 'Elphidran',
  'Эльпидран Акуа': 'Elphidran Aqua',
  'Пиртиран': 'Pyrin',
  'Пиртиран Нокт': 'Pyrin Noct',
  'Люмиайр': 'Lyleen',
  'Люмиайр Нокт': 'Lyleen Noct',
  'Хелзейр': 'Helzephyr',
  'Азуроб': 'Azurobe',
  'Броншерри': 'Broncherry',
  'Броншерри Акуа': 'Broncherry Aqua',
  'Уловер': 'Wumpo',
  'Уловер Ботан': 'Wumpo Botan',
  'Маммотист': 'Mammorest',
  'Маммотист Кризт': 'Mammorest Cryst',
  'Эйкзерди': 'Eikthyrdeer',
  'Эйкзерди Терра': 'Eikthyrdeer Terra',
  'Шэдоубик': 'Shadowbeak',
  'Реиндрикс': 'Reindrix',
  'Фалерис': 'Faleris',
  'Релакса': 'Relaxaurus',
  'Астогон': 'Astegon',
};

// Функция получения URL изображения пала по имени (русскому или английскому)
function getPalImg(nameOrEng) {
  if (!nameOrEng) return null;
  const raw = String(nameOrEng).trim();

  // 1. Прямой поиск по английскому имени
  let internal = PAL_INTERNAL[raw];
  if (internal) return PAL_IMG_BASE + 'T_' + internal + '_icon_normal.webp';

  // 2. Поиск через русский словарь
  const eng = RU_TO_ENG[raw];
  if (eng && PAL_INTERNAL[eng]) {
    return PAL_IMG_BASE + 'T_' + PAL_INTERNAL[eng] + '_icon_normal.webp';
  }

  // 3. Нечувствительный к регистру поиск по английскому
  const lower = raw.toLowerCase();
  for (const [k, v] of Object.entries(PAL_INTERNAL)) {
    if (k.toLowerCase() === lower) {
      return PAL_IMG_BASE + 'T_' + v + '_icon_normal.webp';
    }
  }

  // 4. Нечувствительный к регистру поиск по русскому
  for (const [k, v] of Object.entries(RU_TO_ENG)) {
    if (k.toLowerCase() === lower && PAL_INTERNAL[v]) {
      return PAL_IMG_BASE + 'T_' + PAL_INTERNAL[v] + '_icon_normal.webp';
    }
  }

  return null;
}

// Генерация HTML-тега изображения
function palImgTag(nameOrEng, size, alt, extraStyle) {
  size = size || 64;
  const url = getPalImg(nameOrEng);
  const fallbackSvg = 'data:image/svg+xml,' + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size + '" viewBox="0 0 ' + size + ' ' + size + '">' +
    '<rect width="' + size + '" height="' + size + '" rx="10" fill="#21262d"/>' +
    '<text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" font-size="' + Math.floor(size * 0.42) + '" fill="#8b949e">🐾</text>' +
    '</svg>'
  );

  const style = 'width:' + size + 'px;height:' + size + 'px;min-width:' + size + 'px;border-radius:10px;object-fit:cover;background:#161b22;border:1px solid rgba(255,255,255,0.08);box-shadow:0 2px 8px rgba(0,0,0,0.35);' + (extraStyle || '');

  if (!url) {
    return '<img src="' + fallbackSvg + '" alt="' + (alt || nameOrEng || '') + '" style="' + style + '" loading="lazy">';
  }

  return '<img src="' + url + '" alt="' + (alt || nameOrEng || '') + '" style="' + style + '" loading="lazy" onerror="this.onerror=null;this.src=\'' + fallbackSvg + '\'">';
}

if (typeof window !== 'undefined') {
  window.getPalImg = getPalImg;
  window.palImgTag = palImgTag;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { getPalImg, palImgTag };
}
